"""add comic_issue

Revision ID: 151fd024a39b
Revises: 948750862568
Create Date: 2026-05-05 17:17:21.478828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151fd024a39b'
down_revision = '948750862568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=20), nullable=False),
    sa.Column('issue_title', sa.String(length=255), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('cover_date', sa.Date(), nullable=True),
    sa.Column('designation', sa.String(length=30), nullable=False),
    sa.Column('physical_binding', sa.String(length=20), nullable=False),
    sa.Column('trim_size', sa.String(length=20), nullable=True),
    sa.Column('trim_size_custom', sa.String(length=100), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('upc_isbn', sa.String(length=30), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('wookieepedia_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['comic_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comic_issue')
    # ### end Alembic commands ###
