"""add segment_relationship

Revision ID: 1fcdd7ae5eb2
Revises: 0d0915143c75
Create Date: 2026-05-05 17:21:59.089400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fcdd7ae5eb2'
down_revision = '0d0915143c75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('segment_relationship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_segment_id', sa.Integer(), nullable=False),
    sa.Column('derived_segment_id', sa.Integer(), nullable=False),
    sa.Column('reproduction_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['derived_segment_id'], ['comic_segment.id'], ),
    sa.ForeignKeyConstraint(['source_segment_id'], ['comic_segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segment_relationship')
    # ### end Alembic commands ###
