"""add credit

Revision ID: 24261f1e0618
Revises: 1fcdd7ae5eb2
Create Date: 2026-05-05 17:22:31.463951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24261f1e0618'
down_revision = '1fcdd7ae5eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('alias_id', sa.Integer(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('is_uncredited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alias_id'], ['creator_alias.id'], ),
    sa.ForeignKeyConstraint(['creator_id'], ['creator.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['comic_issue.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['comic_segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit')
    # ### end Alembic commands ###
