"""add comic_series

Revision ID: 948750862568
Revises: f1a2b3c4d5e6
Create Date: 2026-05-05 17:16:07.804561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948750862568'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('series_type', sa.String(length=30), nullable=False),
    sa.Column('continuity', sa.String(length=10), nullable=False),
    sa.Column('era_id', sa.Integer(), nullable=True),
    sa.Column('is_timeline_spanning', sa.Boolean(), nullable=False),
    sa.Column('publisher_id', sa.Integer(), nullable=False),
    sa.Column('imprint_id', sa.Integer(), nullable=True),
    sa.Column('age_rating', sa.String(length=10), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['era_id'], ['era.id'], ),
    sa.ForeignKeyConstraint(['imprint_id'], ['imprint.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comic_series')
    # ### end Alembic commands ###
