"""add character_appearance, persona first_appearance_fk

Revision ID: af560c9a0e4d
Revises: 24261f1e0618
Create Date: 2026-05-05 17:23:02.401474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af560c9a0e4d'
down_revision = '24261f1e0618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_appearance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=True),
    sa.Column('appearance_type', sa.String(length=15), nullable=False),
    sa.Column('is_uncredited', sa.Boolean(), nullable=False),
    sa.Column('archivist_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['character_persona.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['comic_segment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_persona', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_persona_first_appearance_segment', 'comic_segment', ['first_appearance_segment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_persona', schema=None) as batch_op:
        batch_op.drop_constraint('fk_persona_first_appearance_segment', type_='foreignkey')

    op.drop_table('character_appearance')
    # ### end Alembic commands ###
